
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSUMARESTAleftMULTIPLICACIONDIVISIONINT FLOAT NAME RESTA SUMA DIVISION MULTIPLICACION EQUALS LPAREN RPAREN\n    calc : expression\n         | var_assign\n         | empty\n    \n    var_assign : NAME EQUALS expression\n        \n    \n    expression : expression MULTIPLICACION expression\n               | expression DIVISION expression\n               | expression SUMA expression\n               | expression RESTA expression\n    expression : LPAREN expression RPAREN\n    expression : INT\n               | FLOAT\n    \n    expression : NAME\n    \n    empty : \n    '
    
_lr_action_items = {'LPAREN':([0,5,9,10,11,12,15,],[5,5,5,5,5,5,5,]),'INT':([0,5,9,10,11,12,15,],[6,6,6,6,6,6,6,]),'FLOAT':([0,5,9,10,11,12,15,],[7,7,7,7,7,7,7,]),'NAME':([0,5,9,10,11,12,15,],[8,14,14,14,14,14,14,]),'$end':([0,1,2,3,4,6,7,8,14,16,17,18,19,20,21,],[-13,0,-1,-2,-3,-10,-11,-12,-12,-5,-6,-7,-8,-9,-4,]),'MULTIPLICACION':([2,6,7,8,13,14,16,17,18,19,20,21,],[9,-10,-11,-12,9,-12,-5,-6,9,9,-9,9,]),'DIVISION':([2,6,7,8,13,14,16,17,18,19,20,21,],[10,-10,-11,-12,10,-12,-5,-6,10,10,-9,10,]),'SUMA':([2,6,7,8,13,14,16,17,18,19,20,21,],[11,-10,-11,-12,11,-12,-5,-6,-7,-8,-9,11,]),'RESTA':([2,6,7,8,13,14,16,17,18,19,20,21,],[12,-10,-11,-12,12,-12,-5,-6,-7,-8,-9,12,]),'RPAREN':([6,7,13,14,16,17,18,19,20,],[-10,-11,20,-12,-5,-6,-7,-8,-9,]),'EQUALS':([8,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'expression':([0,5,9,10,11,12,15,],[2,13,16,17,18,19,21,]),'var_assign':([0,],[3,]),'empty':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','calc.py',62),
  ('calc -> var_assign','calc',1,'p_calc','calc.py',63),
  ('calc -> empty','calc',1,'p_calc','calc.py',64),
  ('var_assign -> NAME EQUALS expression','var_assign',3,'p_var_assign','calc.py',71),
  ('expression -> expression MULTIPLICACION expression','expression',3,'p_expression','calc.py',79),
  ('expression -> expression DIVISION expression','expression',3,'p_expression','calc.py',80),
  ('expression -> expression SUMA expression','expression',3,'p_expression','calc.py',81),
  ('expression -> expression RESTA expression','expression',3,'p_expression','calc.py',82),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calc.py',88),
  ('expression -> INT','expression',1,'p_expression_int_float','calc.py',93),
  ('expression -> FLOAT','expression',1,'p_expression_int_float','calc.py',94),
  ('expression -> NAME','expression',1,'p_expression_var','calc.py',100),
  ('empty -> <empty>','empty',0,'p_empty','calc.py',109),
]
